/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.edu.todopc.forms;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import sv.com.edu.todopc.dto.Revistas;
import sv.com.edu.todopc.utils.RevistasCRUD;

/**
 *
 * @author patym
 */
public class FormRevistas extends javax.swing.JFrame {

    static final Logger log = Logger.getLogger(FormRevistas.class);
    
    /**
     * Creates new form FormRevistas
     */
    public FormRevistas() throws ParseException {
        initComponents();
        RevistasCRUD revistasCRUD = new RevistasCRUD();
        tblDatos.setModel(revistasCRUD.selectAllRevistas());
            log.info("Primera lectura de datos al grid");
        
        //Metodo de seteo de botones 
        defaultBtn();
        
        //Metodo que controla la habilitacion de los campos
        editionTxt(false);
    }

    public void editionTxt(Boolean editable){
        if(editable){
            txtTitulo.setEditable(true);
            txtEditorial.setEditable(true);
            txtPeriodicidad.setEditable(true);
            txtfechPub.setEditable(true);
            txtUniDisp.setEditable(true);
            txtCorrelativo.setEditable(false);
            
        }else{
            txtTitulo.setEditable(false);
            txtEditorial.setEditable(false);
            txtPeriodicidad.setEditable(false);
            txtfechPub.setEditable(false);
            txtUniDisp.setEditable(false);
            txtCorrelativo.setEditable(false);
            
        }
        
    }
    
    
    public void cleanTxt(){
        txtTitulo.setText("");
        txtEditorial.setText("");
        txtPeriodicidad.setText("");
        txtfechPub.setText("");
        txtUniDisp.setText("");
        txtCorrelativo.setText("");
    }
    
    public void defaultBtn(){
       btnNuevo.setEnabled(true);
       btnEditar.setEnabled(true);
       btnEliminar.setEnabled(true);
       
       btnGuardar.setEnabled(false);
       btnActualizar.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPeriodicidad = new javax.swing.JTextField();
        txtUniDisp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCorrelativo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtfechPub = new javax.swing.JFormattedTextField();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 56, 66));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 197, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MEDIATECA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5 ", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDatosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel5.setText("Titulo:");

        jLabel8.setText("Editorial:");

        txtEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialActionPerformed(evt);
            }
        });

        jLabel9.setText("Periodicidad:");

        jLabel10.setText("Fecha de publicación (dd/mm/aaaa):");

        jLabel11.setText("Unidades disponibles");

        txtUniDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniDispActionPerformed(evt);
            }
        });

        jLabel12.setText("Correlativo:");

        txtCorrelativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorrelativoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Mantenimiento de Revistas");

        txtfechPub.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtfechPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechPubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnNuevo)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnEditar)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnEliminar))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnGuardar)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnActualizar)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel5)
                                                    .addComponent(txtfechPub, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(88, 88, 88)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(txtUniDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(17, 17, 17)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(211, 211, 211))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUniDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnGuardar)
                    .addComponent(jButton2))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       btnGuardar.setEnabled(true);
       btnActualizar.setEnabled(false);
       cleanTxt();
       editionTxt(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
       int selectedRowIndex = tblDatos.getSelectedRow();
       
       SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date date = null;
        try {
            date = format.parse(txtfechPub.getText());
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(Level.SEVERE, null, ex);
        }
        Date dateTransform = new Date(date.getTime());
       
       Revistas r = new Revistas(null, txtTitulo.getText(), txtEditorial.getText(), txtPeriodicidad.getText(), dateTransform, txtUniDisp.getText(), txtCorrelativo.getText());
       RevistasCRUD revistas = new RevistasCRUD();
       int rowsUpdate = revistas.update(r);
       
       if (txtTitulo.getText().contentEquals("") || txtEditorial.getText().contentEquals("") || txtPeriodicidad.getText().contentEquals("") || txtUniDisp.getText().contentEquals(""))
       {
            log.error("Error. Algun campo esta vacío");
            JOptionPane.showConfirmDialog(null, "Uno o varios campos se encuentran vacíos. Favor completar el formulario", "Validación de Formulario", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
       }
       else
       {
            if(rowsUpdate>0){
                log.info("Registro actualizado correctamente");
                JOptionPane.showConfirmDialog(null, "Registro actualizado correctamente", "Actualización de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
                 try {
                     tblDatos.setModel(revistas.selectAllRevistas());
                 } catch (ParseException ex) {
                     java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(Level.SEVERE, null, ex);
                 }
                cleanTxt();
                defaultBtn();
            }else{
                log.error("No se ha encontrado ningun registro con el Correlativo " + model.getValueAt(selectedRowIndex, 0));
                JOptionPane.showConfirmDialog(null, "No se ha encontrado ningún registro con el Correlativo " + model.getValueAt(selectedRowIndex, 0) + ", por favor contactarse con el administrador ", "Eliminación de Registro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE,null);
            }
       }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtUniDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniDispActionPerformed

    private void txtCorrelativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorrelativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorrelativoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date date = null;
        try {
            date = format.parse(txtfechPub.getText());
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(Level.SEVERE, null, ex);
        }
        Date dateTransform = new Date(date.getTime());
       
        
       Revistas r = new Revistas(txtTitulo.getText(), txtEditorial.getText(), txtPeriodicidad.getText(), dateTransform, txtUniDisp.getText());
        RevistasCRUD revistas = new RevistasCRUD();
       int rowsSave = revistas.insert(r);
       
       if (txtTitulo.getText().contentEquals("") || txtEditorial.getText().contentEquals("") || txtPeriodicidad.getText().contentEquals("") || txtUniDisp.getText().contentEquals(""))
       {
            log.error("Error. Algun campo esta vacío");
            JOptionPane.showConfirmDialog(null, "Uno o varios campos se encuentran vacíos. Favor completar el formulario", "Validación de Formulario", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
       }
       else
       {
            if(rowsSave>0){
                log.info("Datos guardados correctamente!");
                JOptionPane.showConfirmDialog(null, "Registro guardado correctamente", "Almacenamiento de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
                 try {
                     tblDatos.setModel(revistas.selectAllRevistas());
                 } catch (ParseException ex) {
                     java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(Level.SEVERE, null, ex);
                 }
                cleanTxt();
                defaultBtn();

            }else{
                log.error("No se ha podido guardar el registro, por favor contactarse con el administrador ");
                JOptionPane.showConfirmDialog(null, "No se ha podido guardar el registro, por favor contactarse con el administrador ", "Almacenamiento de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
            }
       }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         if(!txtCorrelativo.getText().equals("")){
            btnGuardar.setEnabled(false);
            btnActualizar.setEnabled(true);
            editionTxt(true);
        }else{
            log.error("Se ha presionado el boton Editar sin haber seleccionado un registro!");
            JOptionPane.showConfirmDialog(null, "Por favor seleccione un registro", "Edición de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE,null);
            defaultBtn();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
       int selectedRowIndex = tblDatos.getSelectedRow();
       
       if(selectedRowIndex < 0){
           log.error("Se ha presionado el boton Eliminar sin haber seleccionado un registro!");
           JOptionPane.showConfirmDialog(null, "Por favor seleccione un registro.", "Eliminación de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE,null);
       }else{
           int input = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el registro "+ model.getValueAt(selectedRowIndex, 0) + "? ", "Eliminación de Registro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null);
        
            if(input == 0){
                log.info("Registro a eliminar: "+ model.getValueAt(selectedRowIndex, 0));
                RevistasCRUD revistas = new RevistasCRUD();
                int countDelete = revistas.delete(model.getValueAt(selectedRowIndex, 0).toString());     
                if(countDelete>0){
                    log.info("Eliminacion correcta del registro: "+ model.getValueAt(selectedRowIndex, 0));
                    JOptionPane.showConfirmDialog(null, "Registro eliminado correctamente", "Eliminación de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
                    try {
                        tblDatos.setModel(revistas.selectAllRevistas());
                    } catch (ParseException ex) {
                        java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                     cleanTxt();
                     defaultBtn();
                }else{
                    log.info("No se ha encontrado ningun registro con el Correlativo " + model.getValueAt(selectedRowIndex, 0));
                    JOptionPane.showConfirmDialog(null, "No se ha encontrado ningún registro con el Correlativo " + model.getValueAt(selectedRowIndex, 0) + ", por favor contactarse con el administrador ", "Eliminación de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
                }
             }
       }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMousePressed
        DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
       int selectedRowIndex = tblDatos.getSelectedRow();
       
       txtCorrelativo.setText(model.getValueAt(selectedRowIndex, 0).toString());
       txtTitulo.setText(model.getValueAt(selectedRowIndex, 1).toString());
       txtEditorial.setText(model.getValueAt(selectedRowIndex, 2).toString());
       txtPeriodicidad.setText(model.getValueAt(selectedRowIndex, 3).toString());
       txtfechPub.setText(model.getValueAt(selectedRowIndex, 4).toString());
       txtUniDisp.setText(model.getValueAt(selectedRowIndex, 5).toString());
       
       log.info("Datos seleccionado: " + model.getValueAt(selectedRowIndex, 0).toString());
       
       //botones
       defaultBtn();
       
       //Metodo que controla la edicion de los txt(True=edita, false=no edita
       editionTxt(false);
    }//GEN-LAST:event_tblDatosMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtfechPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechPubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechPubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormRevistas().setVisible(true);
                } catch (ParseException ex) {
                    java.util.logging.Logger.getLogger(FormRevistas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtCorrelativo;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtPeriodicidad;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUniDisp;
    private javax.swing.JFormattedTextField txtfechPub;
    // End of variables declaration//GEN-END:variables
}
