/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.edu.todopc.forms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import sv.com.edu.todopc.dto.Libros;
import sv.com.edu.todopc.utils.LibrosCRUD;

/**
 *
 * @author patym
 */
public class FormLibros extends javax.swing.JFrame {

    static final Logger log = Logger.getLogger(FormLibros.class);
    
    
    /**
     * Creates new form FormPrueba
     */
    public FormLibros() {
        initComponents();
        LibrosCRUD librosCrud = new LibrosCRUD();
        tblDatos.setModel(librosCrud.selectAllLibros());
        log.info("Primera lectura de datos al grid");
        
        //Metodo de seteo de botones 
        defaultBtn();
        
        //Metodo que controla la habilitacion de los campos
        editionTxt(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumPag = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAnioPub = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUniDisp = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCorrelativo = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 56, 66));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 197, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MEDIATECA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Titulo:");

        jLabel6.setText("Autor:");

        jLabel7.setText("Número de páginas:");

        txtNumPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPagActionPerformed(evt);
            }
        });

        jLabel8.setText("Editorial:");

        jLabel9.setText("ISBN:");

        jLabel10.setText("Año de publicación:");

        jLabel11.setText("Unidades disponibles:");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel12.setText("Correlativo:");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addContainerGap(481, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumPag, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(txtAnioPub, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEditorial)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(txtUniDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnioPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUniDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(jButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDatosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Mantenimiento de Libros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPagActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    
       Libros l = new Libros(txtTitulo.getText(), txtAutor.getText(), txtNumPag.getText(), txtEditorial.getText(), txtIsbn.getText(), txtAnioPub.getText(), txtUniDisp.getText());
       LibrosCRUD libros = new LibrosCRUD();
       int rowsSave = libros.insert(l);
       
       if (txtTitulo.getText().contentEquals("") || txtAutor.getText().contentEquals("") || txtNumPag.getText().contentEquals("") || txtEditorial.getText().contentEquals("") || txtIsbn.getText().contentEquals("")  || txtAnioPub.getText().contentEquals("") || txtUniDisp.getText().contentEquals(""))
       {
            log.error("Error. Algun campo esta vacío");
            JOptionPane.showConfirmDialog(null, "Uno o varios campos se encuentran vacíos. Favor completar el formulario", "Validación de Formulario", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
       }
       else
       { 
            if(rowsSave>0){
                log.info("Datos guardados exitosamente!");
                JOptionPane.showConfirmDialog(null, "Registro guardado correctamente", "Almacenamiento de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
                tblDatos.setModel(libros.selectAllLibros());
                cleanTxt();
                defaultBtn();

            }else{
                log.error("No se ha podido guardar el registro, por favor contactarse con el administrador ");
                JOptionPane.showConfirmDialog(null, "No se ha podido guardar el registro, por favor contactarse con el administrador ", "Almacenamiento de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
            }
       }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMousePressed
       DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
       int selectedRowIndex = tblDatos.getSelectedRow();
       
       txtCorrelativo.setText(model.getValueAt(selectedRowIndex, 0).toString());
       txtTitulo.setText(model.getValueAt(selectedRowIndex, 1).toString());
       txtAutor.setText(model.getValueAt(selectedRowIndex, 2).toString());
       txtNumPag.setText(model.getValueAt(selectedRowIndex, 3).toString());
       txtEditorial.setText(model.getValueAt(selectedRowIndex, 4).toString());
       txtIsbn.setText(model.getValueAt(selectedRowIndex, 5).toString());
       txtAnioPub.setText(model.getValueAt(selectedRowIndex, 6).toString());
       txtUniDisp.setText(model.getValueAt(selectedRowIndex, 7).toString());
     //  txtId.setText(model.getValueAt(selectedRowIndex, 0).toString());

       log.info("Registro seleccionado: " + model.getValueAt(selectedRowIndex, 0).toString());
       
       //botones
       defaultBtn();
       
       //Metodo que controla la edicion de los txt(True=edita, false=no edita
       editionTxt(false);
    }//GEN-LAST:event_tblDatosMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
       int selectedRowIndex = tblDatos.getSelectedRow();
       
       if(selectedRowIndex < 0){
           log.error("Se ha presionado el boton Eliminar sin haber seleccionado un registro!");
           JOptionPane.showConfirmDialog(null, "Por favor seleccione un registro.", "Eliminación de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE,null);
       }else{
           int input = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el registro "+ model.getValueAt(selectedRowIndex, 0) + "? ", "Eliminación de Registro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null);
        
            if(input == 0){
                log.info("Registro a eliminar: "+ model.getValueAt(selectedRowIndex, 0));
                LibrosCRUD libros = new LibrosCRUD();
                int countDelete = libros.delete(model.getValueAt(selectedRowIndex, 0).toString());     
                if(countDelete>0){
                    log.info("Eliminacion correcta del registro: "+ model.getValueAt(selectedRowIndex, 0));
                    JOptionPane.showConfirmDialog(null, "Registro eliminado correctamente", "Eliminación de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
                     tblDatos.setModel(libros.selectAllLibros());
                     cleanTxt();
                     defaultBtn();
                }else{
                    log.info("No se ha encontrado ningun registro con el Correlativo " + model.getValueAt(selectedRowIndex, 0));
                    JOptionPane.showConfirmDialog(null, "No se ha encontrado ningun registro con el Correlativo " + model.getValueAt(selectedRowIndex, 0) + ", por favor contactarse con el administrador ", "Eliminación de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
                }
             }
       }
       
       
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        if(!txtCorrelativo.getText().equals("")){
            btnGuardar.setEnabled(false);
            btnActualizar.setEnabled(true);
            editionTxt(true);
            
        }else{
            log.error("Se ha presionado el boton Editar sin haber seleccionado un registro!");
            JOptionPane.showConfirmDialog(null, "Por favor seleccione un registro", "Edición de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE,null);
            defaultBtn();
        }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       btnGuardar.setEnabled(true);
       btnActualizar.setEnabled(false);
       cleanTxt();
       editionTxt(true);
       
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    
       DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
       int selectedRowIndex = tblDatos.getSelectedRow();
       
       Libros l = new Libros(null, txtTitulo.getText(), txtAutor.getText(), txtNumPag.getText(), txtEditorial.getText(), txtIsbn.getText(), txtAnioPub.getText(), txtUniDisp.getText(),txtCorrelativo.getText());
       LibrosCRUD libros = new LibrosCRUD();
       int rowsUpdate = libros.update(l);
       
       if (txtTitulo.getText().contentEquals("") || txtAutor.getText().contentEquals("") || txtNumPag.getText().contentEquals("") || txtEditorial.getText().contentEquals("") || txtIsbn.getText().contentEquals("")  || txtAnioPub.getText().contentEquals("") || txtUniDisp.getText().contentEquals(""))
       {
            log.error("Error. Algun campo esta vacío");
            JOptionPane.showConfirmDialog(null, "Uno o varios campos se encuentran vacíos. Favor completar el formulario", "Validación de Formulario", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
       }
       else
       {
            if(rowsUpdate>0){
                log.info("Registro actualizado correctamente");
                JOptionPane.showConfirmDialog(null, "Registro actualizado correctamente", "Actualización de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
                tblDatos.setModel(libros.selectAllLibros());
                cleanTxt();
                defaultBtn();
            }else{
                log.error("No se ha encotrado ningun registro con el Id " + model.getValueAt(selectedRowIndex, 1));
                JOptionPane.showConfirmDialog(null, "No se ha encontrado ningún registro con el Correlativo " + model.getValueAt(selectedRowIndex, 1) + ", por favor contactarse con el administrador ", "Eliminación de Registro", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE,null);
            }
       }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void editionTxt(Boolean editable){
        if(editable){
            txtTitulo.setEditable(true);
            txtAutor.setEditable(true);
            txtNumPag.setEditable(true);
            txtEditorial.setEditable(true);
            txtIsbn.setEditable(true);
            txtAnioPub.setEditable(true);
            txtUniDisp.setEditable(true);
            txtCorrelativo.setEditable(false);
            
        }else{
            txtTitulo.setEditable(false);
            txtAutor.setEditable(false);
            txtNumPag.setEditable(false);
            txtEditorial.setEditable(false);
            txtIsbn.setEditable(false);
            txtAnioPub.setEditable(false);
            txtUniDisp.setEditable(false);
            txtCorrelativo.setEditable(false);
        }
        
    }
    
    
    public void cleanTxt(){
        txtTitulo.setText("");
        txtAutor.setText("");
        txtNumPag.setText("");
        txtEditorial.setText("");
        txtIsbn.setText("");
        txtAnioPub.setText("");
        txtUniDisp.setText("");
        txtCorrelativo.setText("");
    }
    
    public void defaultBtn(){
       btnNuevo.setEnabled(true);
       btnEditar.setEnabled(true);
       btnEliminar.setEnabled(true);
       
       btnGuardar.setEnabled(false);
       btnActualizar.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrueba().setVisible(true);
           
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLibros().setVisible(true);
           
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnActualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtAnioPub;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCorrelativo;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNumPag;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUniDisp;
    // End of variables declaration//GEN-END:variables
}
